apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa

---

apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth: 
        kubernetes:
          role: "eso-role"
          mountPath: "kubernetes"
          serviceAccountRef:
            name: vault-sa

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: server-values
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: {{ .Values.server.appsecret }}
  dataFrom:
  - extract:
      key: "secret/app/server-values"

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-values
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: {{ .Values.db.dbsecret }}
  dataFrom:
  - extract:
      key: "secret/db/db-values"

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: registry-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: {{ .Values.server.imagesecret }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: {{`"{{ .raw_token | b64dec }}"`}}
  data:
  - secretKey: raw_token
    remoteRef:
      key: "secret/app/registry-secret"
      property: data