apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.serviceName }} 
spec:
  selector:
    app: {{ .Values.server.container.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.container.port }}
      targetPort: {{ .Values.server.container.port }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.server.name }}
  labels:
    app: js-server
spec:
  replicas: {{ .Values.server.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.server.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.server.container.name }}
    spec:
      containers:
        - name: {{ .Values.server.container.name }}
          image: "{{ .Values.server.container.image }}:{{ .Values.server.container.tag }}"
          ports:
            - containerPort: {{ .Values.server.container.port }}
          volumeMounts:
          - name: shared-uploads
            mountPath: /app/uploads

          envFrom:
          - secretRef:
              name: {{ .Values.server.appsecret }}

          readinessProbe:
            httpGet:
              path: /status
              port: {{ .Values.server.container.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: / 
              port: {{ .Values.server.container.port }}
            initialDelaySeconds: 15
            periodSeconds: 30

      imagePullSecrets:
      - name: {{ .Values.server.imagesecret }}

      volumes:
        - name: shared-uploads
          persistentVolumeClaim:
            claimName: {{ .Values.server.pvcname }}


# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{ .Values.server.saname }}
#   labels:
#     app: {{ .Values.server.container.name }}

# ---
      # annotations:
      #   vault.hashicorp.com/agent-inject: "true"
      #   vault.hashicorp.com/role: "server-role"
      #   vault.hashicorp.com/agent-inject-secret-servervalues: "secret/app/server-values"
      #   vault.hashicorp.com/agent-inject-template-servervalues: |
      #     {{ `{{- with secret "secret/data/app/server-values" -}}` }}
      #     {{ `{{- range $key, $value := .Data.data }}` }}
      #     export {{`{{$key}}`}}="{{`{{$value}}`}}"
      #     {{ `{{- end }}` }}
      #     {{ `{{- end -}}` }}
      # serviceAccountName: {{ .Values.server.saname }}
          # command: ["/bin/sh"]
          # args:
          #   - -c
          #   - |
          #     set -e
          #     source /vault/secrets/servervalues
          #     exec node /app/server/index.js